version: "3"
services:
  app:
    container_name: nest-starter
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - nest-starter
networks:
  nest-starter:
